'use strict';
const db=FF14_CATALOG,e=FF14Core.createEngine(db),S=FF14State,$=id=>document.getElementById(id);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const h=escapeHtml,fmt=n=>Number(n||0).toLocaleString('zh-TW'),byId=id=>e.items.get(Number(id));
let state=S.empty(),plan=null,zero=null,branchPlan=null,tab='home',collectionPage=0,importPending=null,stockPage=0,historyPage=0;
let stockQueried=false,targetPage=0;
let stockFilter={q:'',categories:[],from:'',to:'',unknown:true,owned:false},collectionFilter={q:'',kind:'recipe',only:false,columns:{}};
try{const stored=localStorage.getItem(S.KEY);if(stored)state=S.validate(JSON.parse(stored));else if(globalThis.FF14_BOOTSTRAP)state=S.validate(globalThis.FF14_BOOTSTRAP);}catch(err){$('notice').className='warning';$('notice').textContent='原備份讀取失敗，尚未覆蓋瀏覽器資料。請先匯出原資料或使用備份恢復：'+err.message;}
let storageBlocked=!!$('notice').textContent;
function notify(message,error=false){$('notice').className=error?'warning':'inline-note';$('notice').textContent=message;}
function save(){if(storageBlocked)throw Error('原資料尚未恢復，禁止覆蓋');try{localStorage.setItem(S.KEY,JSON.stringify(state));$('save-status').textContent='已儲存於此瀏覽器 · '+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'});}catch(err){notify('無法保存，請立即匯出備份：'+err.message,true);throw err;}}
function commit(next){const old=state;state=next;try{save();}catch(err){state=old;throw err;}}
function update(fn){const next=structuredClone(state);fn(next);commit(next);}
function safe(fn){try{return fn();}catch(err){notify(err.message,true);}}
function download(name,text,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function backup(){if(storageBlocked){download('ff14-original-recovery.json',localStorage.getItem(S.KEY)||'{}');return;}download('ff14-workbench-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2));}
const titles={home:['素材製作工坊','製作備料、素材用途、背包盤點與收藏進度。'],a:['指定成品，展開備料','加入這次要做的東西，素材製作工坊會一起計算庫存、批次與缺料。'],b:['從素材，找到收藏用途','先保留完整下游母清單，再把選定目標交給同一套備料計算。'],stock:['盤點背包','填好現貨，讓每一層半成品都能正確切斷上游需求。'],collection:['收藏進度','製作筆記與永久收藏共用介面，各自保留正確的完成身分。'],history:['留下記錄，下次接著做','實際製作、盤點與工作備註，都留在這個素材製作工坊。'],data:['資料與備份','保留備份，也確認配方來源與目前可使用的範圍。']};
function showTab(key){tab=key;document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!=='tab-'+key);document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===key));$('page-title').textContent=titles[key][0];$('crumb').textContent=key==='home'?'首頁':document.querySelector('nav button[data-tab="'+key+'"]').textContent.replace(/^\d+\s*/, '').trim();$('back-home').hidden=key==='home';$('page-description').textContent=titles[key][1];if(key==='stock')renderStock();if(key==='collection')renderCollection();if(key==='history')renderHistory();}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
$('back-home').addEventListener('click',()=>showTab('home'));
document.querySelectorAll('[data-go-home]').forEach(b=>b.addEventListener('click',event=>{event.preventDefault();showTab('home');}));
document.querySelectorAll('[data-home-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.homeTab)));
function itemMatches(id,q){const x=byId(id);return x&&(x.name.includes(q)||String(id)===q);}
function recipeLabel(r){return r.job+' · Lv.'+r.level+' · '+r.scope+' · 每批 '+r.yieldQty+' 個';}
function recipeSearch(){const q=$('target-search').value.trim();if(!q){$('target-results').innerHTML='';return;}const rs=db.recipes.filter(r=>itemMatches(r.item,q)).sort((a,b)=>Number(b.tracked)-Number(a.tracked)||a.level-b.level||a.id-b.id).slice(0,35);$('target-results').innerHTML=rs.map(r=>`<div class="search-row"><div>${h(e.name(r.item))}<small>${h(recipeLabel(r))}${r.quest?' · 有任務条件':''}${r.expert?' · 專家配方':''}${r.specialist?' · 需專用條件':''}</small></div><button data-add="${r.id}">加入</button></div>`).join('')||'<div class="empty">沒有符合的配方。</div>';}
$('target-query').addEventListener('submit',event=>{event.preventDefault();safe(recipeSearch);});
$('target-results').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-add]');if(!b)return;const recipe=Number(b.dataset.add);update(s=>{s.targets.push({mode:'craft',recipe,qty:1});s.targets=e.normalize(s.targets);});renderTargets();calculate();notify('已加入本次目標。');}));
function renderTargets(){const ts=state.targets,pages=Math.max(1,Math.ceil(ts.length/12));targetPage=Math.min(targetPage,pages-1);$('target-count').textContent=ts.length+' 項';$('targets').innerHTML=ts.length?`<div class="table-scroll"><table><thead><tr><th>成品</th><th>目的</th><th>數量</th><th></th></tr></thead><tbody>${ts.slice(targetPage*12,(targetPage+1)*12).map((t,j)=>{const i=targetPage*12+j;return `<tr><td>${h(e.name(t.item||e.recipes.get(t.recipe)?.item))}<span class="target-job">${t.recipe?h(e.recipes.get(t.recipe).job):'使用道具，完成永久登錄'}</span></td><td>${t.mode==='completion'?'製作筆記':t.mode==='unlock'?'永久收藏':'指定製作'}</td><td>${t.mode==='craft'?`<input type="number" min="1" max="999999" aria-label="${h(e.name(t.item))}需求量" value="${t.qty}" data-target-qty="${i}">`:'1'}</td><td><button class="secondary" data-remove="${i}" aria-label="移除${h(e.name(t.item))}">移除</button></td></tr>`;}).join('')}</tbody></table></div>${routePager('target',targetPage,ts.length,12)}`:'<div class="empty">從上方搜尋，加入第一個成品。</div>';}
$('targets').addEventListener('click',event=>safe(()=>{const jump=event.target.closest('[data-target-page]');if(jump){targetPage=Math.max(0,Math.min(Math.ceil(state.targets.length/12)-1,Number(jump.dataset.targetPage)));renderTargets();return;}const b=event.target.closest('[data-remove]');if(!b)return;update(s=>s.targets.splice(Number(b.dataset.remove),1));renderTargets();calculate();}));
$('targets').addEventListener('submit',event=>{if(event.target.id!=='target-jump')return;event.preventDefault();safe(()=>jumpRoutePage('target',12,state.targets.length,targetPage,n=>targetPage=n,renderTargets));});
$('targets').addEventListener('change',event=>safe(()=>{if(!event.target.matches('[data-target-qty]'))return;const qty=FF14Core.integer(event.target.value);if(!qty)throw Error('目標數量至少為 1');update(s=>s.targets[Number(event.target.dataset.targetQty)].qty=qty);calculate();}));
function calculate(){plan=null;zero=null;branchPlan=null;$('route-issues').innerHTML='';try{plan=e.solve(state.targets,state.inventory,state.preferences);zero=e.solve(state.targets,{},state.preferences);branchPlan=buildBranchPlan(plan);renderPlan();}catch(err){renderPlan();const d=err.detail||{};$('route-issues').innerHTML=`<div class="error">${h(err.message)}${d.choices?`<div class="route-choice">${d.choices.map(r=>`<button class="secondary" data-route-item="${d.item}" data-route="${r.id}">${h(recipeLabel(r))}<small> ${r.materials.filter(([id])=>byId(id)?.category!=='水晶').map(([id,q])=>h(e.name(id))+' ×'+q).join('、')}</small></button>`).join('')}</div>`:''}</div>`;}}
$('calculate').addEventListener('click',calculate);
$('route-issues').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-route]');if(!b)return;update(s=>s.preferences[b.dataset.routeItem]=Number(b.dataset.route));calculate();}));
const categoryOrder=['鍊金原料','食材','木材','皮革','骨材','石材','金屬','布料','水產品','其他'];
function table(headers,rows){return rows.length?`<div class="table-scroll"><table><thead><tr>${headers.map(x=>'<th>'+h(x)+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')}</tbody></table></div>`:'<div class="empty">目前沒有項目。</div>';}
function buildBranchPlan(p){
 const roots=new Map(p.rows.filter(r=>!r.pureTarget&&r.direct>0).map(r=>[r.item,null])),incoming=new Map(),nodes=[];
 const make=(item,qty)=>{const n={item,qty,stock:0,sharedIn:0,sharedOut:0,batches:0,produced:0,surplus:0,children:[],plans:[]};nodes.push(n);return n;};
 for(const r of p.rows){
  if(r.pureTarget)continue;
  const list=roots.has(r.item)?[make(r.item,r.need)]:(incoming.get(r.item)||[]);
  if(roots.has(r.item))roots.set(r.item,list[0]);
  if(!list.length)continue;
  if(list.reduce((sum,n)=>sum+n.qty,0)!==r.need)throw Error('分支需求驗算失敗：'+e.name(r.item));
  let stock=r.usedStock;const batches=r.plans.map(([id,q])=>({recipe:e.recipes.get(id),left:q})),pool=[];
  const consume=(n,qty)=>{for(const chunk of pool){const take=Math.min(qty,chunk.qty);chunk.qty-=take;qty-=take;if(chunk.node!==n){chunk.node.sharedOut+=take;n.sharedIn+=take;}if(!qty)break;}return qty;};
  list.forEach((n,i)=>{
   n.stock=Math.min(n.qty,stock);stock-=n.stock;let gap=consume(n,n.qty-n.stock);
   for(const batch of batches){if(!batch.left)continue;const count=i===list.length-1?batch.left:Math.min(batch.left,Math.ceil(gap/batch.recipe.yieldQty));if(!count)continue;batch.left-=count;n.plans.push([batch.recipe.id,count]);n.batches+=count;n.produced+=count*batch.recipe.yieldQty;pool.push({node:n,qty:count*batch.recipe.yieldQty});gap=consume(n,gap);}
   if(gap&&p.chosen[r.item])throw Error('分支產出驗算失敗：'+e.name(r.item));
   for(const [id,count] of n.plans)for(const [item,perBatch] of e.recipes.get(id).materials){if(byId(item)?.category==='水晶')continue;const child=make(item,perBatch*count);child.recipe=id;child.reference=roots.has(item);n.children.push(child);if(!child.reference){if(!incoming.has(item))incoming.set(item,[]);incoming.get(item).push(child);}}
  });
  for(const chunk of pool)chunk.node.surplus+=chunk.qty;
 }
 return {roots,nodes};
}
function routePager(prefix,page,count,size){const pages=Math.max(1,Math.ceil(count/size)),active=count>0;return `<div class="pager list-pager"><button type="button" class="secondary" id="${prefix}-first" data-${prefix}-page="0" ${!active||page===0?'disabled':''}>第一頁</button><button type="button" class="secondary" id="${prefix}-prev" data-${prefix}-page="${page-1}" ${!active||page===0?'disabled':''}>上一頁</button><form class="page-jump" id="${prefix}-jump"><label>第 <input type="number" aria-label="${prefix==='target'?'目標':'下游母清單'}頁碼" id="${prefix}-page-number" min="1" max="${pages}" step="1" value="${page+1}" ${!active?'disabled':''}> 頁</label><span>/ ${pages} 頁 · 全部 ${count} 項</span><button type="submit" class="secondary" ${!active?'disabled':''}>跳頁</button></form><button type="button" class="secondary" id="${prefix}-next" data-${prefix}-page="${page+1}" ${!active||page+1>=pages?'disabled':''}>下一頁</button><button type="button" class="secondary" id="${prefix}-last" data-${prefix}-page="${pages-1}" ${!active||page+1>=pages?'disabled':''}>最後一頁</button></div>`;}
function jumpRoutePage(prefix,size,count,current,set,render){const raw=$(`${prefix}-page-number`).value.trim(),n=Number(raw),pages=Math.max(1,Math.ceil(count/size));if(!/^\d+$/.test(raw)||!Number.isSafeInteger(n)||n<1||n>pages){$(`${prefix}-page-number`).value=String(current+1);throw Error(`頁碼請輸入 1～${pages} 的整數`);}set(n-1);render();}
function renderPlan(){
 $('stats').innerHTML=plan?[['製作批數',plan.crafts.reduce((s,c)=>s+c.batches,0)],['底材缺料種類',plan.raw.filter(r=>r.shortage>0).length],['現貨已抵扣種類',plan.rows.filter(r=>r.usedStock>0).length],['目標數',plan.targets.length]].map(([label,n])=>`<div class="stat"><strong>${fmt(n)}</strong><span>${label}</span></div>`).join(''):'<div class="empty">加入目標後顯示計算結果。</div>';
 if(!plan){for(const id of ['tree','shortages','crafts','zero-raw'])$(id).innerHTML='<div class="empty">沒有可顯示的計算結果。</div>';return;}
 const rowMap=new Map(plan.rows.map(r=>[r.item,r]));
 const rootRows=plan.rows.filter(r=>!r.pureTarget&&r.direct>0);const roots=new Set(rootRows.map(r=>r.item));
 function gate(n,depth=0){if(!n||!plan.chosen[n.item])return '';const recipe=e.recipes.get(plan.chosen[n.item]),sig=x=>JSON.stringify(x.materials.filter(([id])=>byId(id)?.category!=='水晶').slice().sort((a,b)=>a[0]-b[0])),eq=e.producers.get(n.item).filter(x=>x.yieldQty===recipe.yieldQty&&sig(x)===sig(recipe)),jobs=[...new Set(eq.map(x=>x.job))].join('／');
  const supply=`此處需求 ×${fmt(n.qty)}；現貨抵扣 ×${fmt(n.stock)}${n.sharedIn?'；由合併製作產出供應 ×'+fmt(n.sharedIn):''}`;
  return `<div class="gate" data-gate-item="${n.item}" data-branch-need="${n.qty}"><b>若不足：【${h(jobs)}】</b><div>${supply}</div><div>${n.batches?`製作 ${n.batches} 批 ｜ 產出 ×${fmt(n.produced)} ｜ 此處使用 ×${fmt(n.qty-n.stock-n.sharedIn)}${n.sharedOut?' ｜ 分配其他用途 ×'+fmt(n.sharedOut):''} ｜ 剩餘 ×${fmt(n.surplus)}`:n.sharedIn?'這份上游由合併製作供應，不另加製作批次。':'現貨足夠，這份上游已歸零。'}</div>${n.children.map(child=>{const cross=byId(child.item)?.category!==byId(n.item)?.category?'〔'+h(byId(child.item)?.category||'其他')+'〕':'';return `<div class="branch-material" data-branch-item="${child.item}" data-branch-qty="${child.qty}" style="margin-left:${Math.min(depth,6)*3}px">${h(e.name(child.item))}${cross} ×${fmt(child.qty)}${child.reference?' <span class="muted">（另有直接用途；其全域缺口在自己的主列集中處理。）</span>':gate(child,depth+1)}</div>`;}).join('')}</div>`;
 }

 const categories=[...new Set(rootRows.map(r=>byId(r.item)?.category||'其他'))].sort((a,b)=>{const ai=categoryOrder.indexOf(a),bi=categoryOrder.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b,'zh-TW');});
 $('tree').innerHTML=categories.map(cat=>`<div class="tree-category"><h3>${h(cat)}</h3>${rootRows.filter(r=>(byId(r.item)?.category||'其他')===cat).map(r=>`<article class="tree-node ${state.review[r.item]?'reviewed':''}"><div class="node-head"><input type="checkbox" aria-label="已檢閱${h(e.name(r.item))}" data-review="${r.item}" ${state.review[r.item]?'checked':''}><strong>${h(e.name(r.item))}</strong><span class="qty">直接需求 ×${fmt(r.direct)}</span><label class="stock-value">現貨 <input type="number" min="0" aria-label="${h(e.name(r.item))}庫存" value="${state.inventory[r.item]||0}" data-stock="${r.item}"></label></div><div class="node-body"><div>${r.reserve?`<div>【本次目標保留】×${r.reserve}</div>`:''}${r.uses.filter(s=>s.direct).map(s=>`<div>→ ${h(e.name(s.parent))} ×${s.output}（本素材 ×${s.qty}）</div>`).join('')}<div class="use">本次總需求 ×${fmt(r.need)}（直接使用 ×${fmt(r.direct)}${r.conditional?'＋補製其他素材 ×'+fmt(r.conditional):''}）；現貨抵扣 ×${fmt(r.usedStock)}</div></div>${gate(branchPlan.roots.get(r.item))}</div></article>`).join('')}</div>`).join('')||'<div class="empty">目前目標沒有直接素材列；請查看底層缺料及製作批次。</div>';
 $('shortages').innerHTML=table(['素材','還缺','已啟用需求','盤點現貨'],plan.raw.filter(r=>r.shortage>0).map(r=>[h(e.name(r.item)),`<strong>${fmt(r.shortage)}</strong>`,fmt(r.need),`<input type="number" min="0" aria-label="${h(e.name(r.item))}庫存" data-stock="${r.item}" value="${state.inventory[r.item]||0}">`]));
 $('crafts').innerHTML=table(['製作物品','批次／產量','加工分配','實際記錄'],plan.crafts.map(c=>{const r=rowMap.get(c.item);return [h(e.name(c.item))+'<div class="inline-note">'+h(c.job)+'</div>',`${c.batches} 批<br>每批 ${c.yieldQty}<br>產出 ${c.produced}`,`保留 ×${r.reserve}<br>投入下游 ×${r.need-r.reserve}<br>批次剩餘 ×${r.surplus}`,`<button class="secondary" data-craft="${c.recipe}" data-batches="${c.batches}">記錄已製作</button>`];}));
 $('zero-raw').innerHTML=table(['分類','原料','從零需求'],(zero?.raw||[]).map(r=>[h(byId(r.item)?.category),h(e.name(r.item)),fmt(r.need)]));
}
document.addEventListener('change',event=>safe(()=>{if(event.target.matches('[data-stock]')){const id=event.target.dataset.stock,n=FF14Core.integer(event.target.value,'庫存');update(s=>s.inventory[id]=n);calculate();if(tab==='stock')renderStock();}if(event.target.matches('[data-review]')){update(s=>s.review[event.target.dataset.review]=event.target.checked);renderPlan();}if(event.target.matches('[data-completion]')){update(s=>s.completion[event.target.dataset.completion]=event.target.checked);renderCollection();renderMother();}}));
$('crafts').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-craft]');if(!b)return;const r=e.recipes.get(Number(b.dataset.craft)),n=Number(b.dataset.batches);if(!window.confirm('確認你已在遊戲中製作 '+e.name(r.item)+' '+n+' 批？\n將扣除已盤點材料、增加成品；不會自動完成永久收藏。'))return;const pure=plan.pureTargets.includes(r.item);const next=S.recordCraft(state,e,r.id,n);if(pure)next.targets=next.targets.filter(t=>!(t.mode==='craft'&&t.recipe===r.id));commit(next);renderTargets();calculate();notify('已保存實際製作記錄與庫存變動。');}));
const stockCategoryOrder=['鍊金原料','食材','木材','皮革','骨材','石材','金屬','布料','水產品','其他'];
const stockEligible=new Set([...db.recipes.filter(r=>r.tracked).map(r=>r.item),...db.unlocks.map(u=>u.item),...db.items.filter(x=>x.category==='水晶').map(x=>x.id)]);
const stockItems=db.items.filter(x=>stockEligible.has(x.id));
const stockCategories=[...new Set(stockItems.map(x=>x.category||'其他'))].sort((a,b)=>{const rank=x=>stockCategoryOrder.includes(x)?stockCategoryOrder.indexOf(x):stockCategoryOrder.length;return rank(a)-rank(b)||a.localeCompare(b,'zh-Hant');});
const categoryChip=c=>`<label class="category-chip"><input type="checkbox" value="${h(c)}" data-stock-category> ${h(c)}</label>`;
const commonStockCategories=[...stockCategoryOrder,'水晶'];
$('stock-categories').innerHTML=stockCategories.filter(c=>commonStockCategories.includes(c)).map(categoryChip).join('')+`<details class="extra-categories"><summary>其他物品種類</summary><div class="category-chips">${stockCategories.filter(c=>!commonStockCategories.includes(c)).map(categoryChip).join('')}</div></details>`;
function syncStockCategoryToggle(){const checks=[...document.querySelectorAll('[data-stock-category]')];$('stock-category-toggle').setAttribute('aria-pressed',String(checks.every(x=>x.checked)));}
$('stock-category-toggle').addEventListener('click',()=>{const checks=[...document.querySelectorAll('[data-stock-category]')],selectAll=!checks.every(x=>x.checked);checks.forEach(x=>x.checked=selectAll);syncStockCategoryToggle();});
$('stock-categories').addEventListener('change',syncStockCategoryToggle);
const knownVersion=x=>/^([2-7])\.X$/.test(x.version||'')?Number(x.version[0]):null;
for(const id of ['stock-version-from','stock-version-to'])$(id).innerHTML='<option value="">不限</option>'+[2,3,4,5,6,7].map(v=>`<option value="${v}">${v}.X</option>`).join('');
const sortedStockItems=[...stockItems].sort((a,b)=>(knownVersion(a)??Infinity)-(knownVersion(b)??Infinity)||a.name.localeCompare(b.name,'zh-Hant',{numeric:true})||a.id-b.id);
function stockMatches(){return sortedStockItems.filter(x=>{const v=knownVersion(x);return (!stockFilter.q||itemMatches(x.id,stockFilter.q))&&(!stockFilter.categories.length||stockFilter.categories.includes(x.category||'其他'))&&(!stockFilter.owned||Object.hasOwn(state.inventory,x.id))&&(v===null?stockFilter.unknown:(!stockFilter.from||v>=Number(stockFilter.from))&&(!stockFilter.to||v<=Number(stockFilter.to)));});}
function renderStock(){if(!stockQueried){$('stock-count').textContent='尚未查詢';$('stock-items').innerHTML='<div class="empty">設定條件後，按「查詢」或 Enter 載入庫存清單。</div>';syncPager('stock',0,0,false);return;}const list=stockMatches(),pages=Math.max(1,Math.ceil(list.length/40));stockPage=Math.min(stockPage,pages-1);$('stock-count').textContent=list.length+' 項';$('stock-items').innerHTML=list.length?`<table class="stock-table"><thead><tr><th>物品</th><th>種類</th><th>版本</th><th>現有數量</th></tr></thead><tbody>${list.slice(stockPage*40,(stockPage+1)*40).map(x=>`<tr data-stock-row="${x.id}"><td><strong>${h(x.name)}</strong><div class="inline-note">ID ${x.id}</div></td><td><span class="material-category">${h(x.category||'其他')}</span></td><td class="version-mark">${knownVersion(x)===null?'未確認':h(x.version)}</td><td><input class="stock-quantity" type="number" min="0" aria-label="${h(x.name)}庫存" data-stock="${x.id}" value="${state.inventory[x.id]||0}"></td></tr>`).join('')}</tbody></table>`:'<div class="empty">沒有符合條件的物品。</div>';syncPager('stock',stockPage,list.length,true);}
$('stock-query').addEventListener('submit',event=>{event.preventDefault();safe(()=>{const from=$('stock-version-from').value,to=$('stock-version-to').value;if(from&&to&&Number(from)>Number(to))throw Error('版本起不能大於版本迄');stockFilter={q:$('stock-search').value.trim(),categories:[...document.querySelectorAll('[data-stock-category]')].filter(x=>x.checked).map(x=>x.value),from,to,unknown:$('stock-unknown').checked,owned:$('stock-owned').checked};stockQueried=true;stockPage=0;renderStock();});});
function syncPager(prefix,page,count,enabled=true){const pages=Math.max(1,Math.ceil(count/40)),active=enabled&&count>0;$(`${prefix}-page`).textContent=enabled?`/ ${pages} 頁 · ${count} 項`:'尚未查詢';const input=$(`${prefix}-page-number`);input.value=String(page+1);input.max=String(pages);input.disabled=!active;for(const end of ['first','prev'])$(`${prefix}-${end}`).disabled=!active||page===0;for(const end of ['next','last'])$(`${prefix}-${end}`).disabled=!active||page+1>=pages;$(`${prefix}-jump`).querySelector('button').disabled=!active;}
function bindPager(prefix,getPage,setPage,getCount,render){for(const end of ['first','prev','next','last'])$(`${prefix}-${end}`).addEventListener('click',()=>{const count=getCount();if(!count)return;const last=Math.ceil(count/40)-1,current=getPage();setPage(end==='first'?0:end==='last'?last:Math.max(0,Math.min(last,current+(end==='next'?1:-1))));render();});$(`${prefix}-jump`).addEventListener('submit',event=>{event.preventDefault();safe(()=>{const count=getCount(),pages=Math.max(1,Math.ceil(count/40)),raw=$(`${prefix}-page-number`).value.trim(),n=Number(raw);if(!count||!/^\d+$/.test(raw)||!Number.isSafeInteger(n)||n<1||n>pages){$(`${prefix}-page-number`).value=String(getPage()+1);throw Error(`頁碼請輸入 1～${pages} 的整數`);}setPage(n-1);render();});});}
bindPager('stock',()=>stockPage,n=>stockPage=n,()=>stockQueried?stockMatches().length:0,renderStock);
function clearMother(){update(s=>s.mother=null);renderMother();}
function materialSearch(){const q=$('material-search').value.trim(),exact=db.items.filter(x=>String(x.id)===q||x.name===q),matches=q?(exact.length?exact:db.items.filter(x=>x.name.includes(q))):[];if(matches.length!==1){clearMother();notify(!q?'請輸入道具名稱或物品 ID。':matches.length?'符合多項道具，請輸入完整名稱或物品 ID。':'沒有符合的道具。',true);return;}const item=matches[0];const mother=e.downstream(item.id,state.completion);const groups=new Map();for(const t of mother.targets){const r=e.recipes.get(t.recipe),label=r?r.job+' · '+Math.floor(r.level/10)*10+'–'+(Math.floor(r.level/10)*10+9)+' 級':'永久收藏';if(!groups.has(label))groups.set(label,[]);groups.get(label).push(t.key);}const batches=[];for(const [label,keys] of groups)for(let i=0;i<keys.length;i+=20)batches.push({id:batches.length+1,label,keys:keys.slice(i,i+20)});update(s=>s.mother={...mother,batches,issuedKeys:[],selected:mother.targets.filter(t=>!t.done).map(t=>t.key),createdAt:new Date().toISOString(),page:0});renderMother();notify('');}
$('material-query').addEventListener('submit',event=>{event.preventDefault();safe(materialSearch);});
function renderMother(){const m=state.mother;if(!m){$('mother').innerHTML='';return;}const current=m.targets.map(t=>({...t,done:state.completion[t.completionKey]===true}));const selected=current.filter(t=>m.selected.includes(t.key)&&!t.done),page=m.page||0,pages=Math.max(1,Math.ceil(current.length/40));let quantityText='選定目標交給 Route A 後，全域計算保留量';try{const p=e.solve(selected,{},state.preferences);quantityText='選定目標從零需求：'+fmt(p.rows.find(r=>r.item===m.start)?.need||0)+' 個 '+e.name(m.start);}catch(err){quantityText='總需求尚待選擇製作路線：'+err.message;}
 let globalText;try{const all=e.solve(current.filter(t=>!t.done),{},state.preferences);globalText='完整母清單未完成目標：'+fmt(all.rows.find(r=>r.item===m.start)?.need||0)+' 個（從零，全域合併批次）';}catch(err){globalText='完整母清單總需求待核對路線：'+err.message;}
 const issued=new Set(m.issuedKeys||[]);const batchHtml=(m.batches||[]).map(batch=>{const ts=current.filter(t=>batch.keys.includes(t.key)&&!t.done);let need='待選路線';try{need=fmt(e.solve(ts,{},state.preferences).rows.find(r=>r.item===m.start)?.need||0);}catch{}return `<div class="search-row"><div>第 ${batch.id} 批 · ${h(batch.label)}<small>${batch.keys.length} 項 · 此批從零需要素材 ${need} 個 · 已交給素材製作工坊 ${batch.keys.filter(k=>issued.has(k)).length} 項</small></div><button class="secondary" data-batch="${batch.id}">選取此批</button></div>`;}).join('');
 $('mother').innerHTML=`<div class="card"><div class="section-head"><div><h2>下游母清單：${h(e.name(m.start))}</h2><p>找到 ${m.recipes.length} 條相關配方；有效收藏目標 ${current.length} 項，已完成 ${current.filter(t=>t.done).length} 項。選取 ${selected.length} 項。</p><button id="send-route-a" ${!selected.length?'disabled':''}>選定目標交給 Route A</button></div></div><div class="warning">${!state.sheetProgressImported&&!Object.keys(state.completion).length?'尚未匯入你的製作圖鑑進度，目前先以未完成列出。<br>':''}${h(globalText)}<br>${h(quantityText)}<br>配方圖涵蓋來源快照全部 Recipe；現行可用性／特殊流程仍需確認。${m.pending.length?' 有 '+m.pending.length+' 個收藏候選尚未納入。':''}</div>${batchHtml?`<details><summary>分批製作 · ${m.batches.length} 批 · 尚未交給素材製作工坊 ${current.filter(t=>!t.done&&!issued.has(t.key)).length} 項</summary><p>批次只方便分段操作；各批從零數量不可相加當成全案需求。素材製作工坊會合併已交入的目標，庫存與批次剩餘只計一次。</p>${batchHtml}</details>`:''}<div class="controls mother-selection-controls"><button class="secondary" id="select-unfinished">選取全部未完成</button><button class="secondary" id="clear-selection">清除選取</button></div>${table(['納入','版本','製作職業','等級','物品名稱','物品分類','完成種類','已完成'],current.slice(page*40,(page+1)*40).map(t=>{const meta={item:t.item,recipes:t.recipe?[e.recipes.get(t.recipe)]:(e.producers.get(t.item)||[])};return [`<input type="checkbox" aria-label="納入${h(e.name(t.item))}" data-mother-select="${h(t.key)}" ${m.selected.includes(t.key)&&!t.done?'checked':''} ${t.done?'disabled':''}>`,h(collectionValue(meta,'version')),h(collectionValue(meta,'job').join('／')||'—'),h(collectionValue(meta,'level').join('／')||'—'),h(e.name(t.item)),h(collectionValue(meta,'category')),t.mode==='completion'?'製作筆記':'永久收藏',`<input type="checkbox" aria-label="完成${h(e.name(t.item))}" data-completion="${h(t.completionKey)}" ${t.done?'checked':''}>`];}))}${routePager('mother',page,current.length,40)}</div>`;
}
$('mother').addEventListener('click',event=>safe(()=>{const id=event.target.id,button=event.target.closest('[data-batch]');const jump=event.target.closest('[data-mother-page]');if(!button&&!jump&&!['select-unfinished','clear-selection','send-route-a'].includes(id))return;if(jump)update(s=>s.mother.page=Math.max(0,Math.min(Math.ceil(s.mother.targets.length/40)-1,Number(jump.dataset.motherPage))));if(button){const batch=state.mother.batches.find(b=>b.id===Number(button.dataset.batch));update(s=>s.mother.selected=batch.keys.filter(k=>{const t=s.mother.targets.find(t=>t.key===k);return s.completion[t.completionKey]!==true;}));}if(id==='select-unfinished')update(s=>s.mother.selected=s.mother.targets.filter(t=>state.completion[t.completionKey]!==true).map(t=>t.key));if(id==='clear-selection')update(s=>s.mother.selected=[]);if(id==='send-route-a'){const ts=state.mother.targets.filter(t=>state.mother.selected.includes(t.key)&&state.completion[t.completionKey]!==true);update(s=>{s.targets=e.normalize([...s.targets,...ts]);s.mother.issuedKeys=[...new Set([...(s.mother.issuedKeys||[]),...ts.map(t=>t.key)])];});targetPage=0;renderTargets();calculate();showTab('a');notify('');}renderMother();}));
$('mother').addEventListener('submit',event=>{if(event.target.id!=='mother-jump')return;event.preventDefault();safe(()=>jumpRoutePage('mother',40,state.mother.targets.length,state.mother.page||0,n=>update(s=>s.mother.page=n),renderMother));});
$('mother').addEventListener('change',event=>safe(()=>{if(!event.target.matches('[data-mother-select]'))return;const key=event.target.dataset.motherSelect;update(s=>{s.mother.selected=s.mother.selected.filter(k=>k!==key);if(event.target.checked)s.mother.selected.push(key);});renderMother();}));
const collectionRows={recipe:db.recipes.filter(r=>r.tracked).map(r=>({item:r.item,key:'recipe_completion:'+r.id,recipes:[r]})),unlock:db.unlocks.map(u=>({item:u.item,key:'permanent_unlock:'+u.item,recipes:e.producers.get(u.item)||[]}))};
const columnKeys=['done','version','job','level','name','category'];
function collectionValue(t,key){const item=byId(t.item);if(key==='done')return state.completion[t.key]===true?'true':'false';if(key==='version')return item?.version||'未確認';if(key==='name')return e.name(t.item);if(key==='category')return item?.category||'其他';return [...new Set(t.recipes.map(r=>key==='job'?r.job:String(r.level)))];}
const allCollectionRows=[...collectionRows.recipe,...collectionRows.unlock];
for(const key of columnKeys.filter(k=>k!=='name')){const options=key==='done'?['true','false']:[...new Set(allCollectionRows.flatMap(t=>collectionValue(t,key)))].sort((a,b)=>a.localeCompare(b,'zh-Hant',{numeric:true}));$(`collection-filter-${key}`).innerHTML='<option value="">全部</option>'+options.map(v=>`<option value="${h(v)}">${key==='done'?(v==='true'?'已完成':'未完成'):h(v)}</option>`).join('');}
function collectionMatches(){const {q,kind,only,columns={}}=collectionFilter;return collectionRows[kind].filter(t=>{if(q&&!itemMatches(t.item,q)||only&&state.completion[t.key]===true)return false;for(const key of ['done','version','category'])if(columns[key]&&collectionValue(t,key)!==columns[key])return false;if(columns.name&&!e.name(t.item).includes(columns.name))return false;if((columns.job||columns.level)&&!t.recipes.some(r=>(!columns.job||r.job===columns.job)&&(!columns.level||String(r.level)===columns.level)))return false;return true;});}
function renderCollection(){const list=collectionMatches(),pages=Math.max(1,Math.ceil(list.length/40));collectionPage=Math.min(collectionPage,pages-1);$('collection-rows').innerHTML=list.length?list.slice(collectionPage*40,(collectionPage+1)*40).map(t=>{const cells=[`<input type="checkbox" aria-label="完成${h(e.name(t.item))}" data-completion="${h(t.key)}" ${state.completion[t.key]?'checked':''}>`,h(collectionValue(t,'version')),h(collectionValue(t,'job').join('／')||'—'),h(collectionValue(t,'level').join('／')||'—'),h(e.name(t.item)),h(collectionValue(t,'category'))];return '<tr>'+cells.map(x=>'<td>'+x+'</td>').join('')+'</tr>';}).join(''):'<tr><td colspan="6" class="empty">目前沒有項目。</td></tr>';syncPager('collection',collectionPage,list.length);}
$('collection-query').addEventListener('submit',event=>{event.preventDefault();collectionFilter={q:$('collection-search').value.trim(),kind:$('collection-kind').value,only:$('only-unfinished').checked,columns:Object.fromEntries(columnKeys.map(key=>[key,$(`collection-filter-${key}`).value.trim()]))};collectionPage=0;renderCollection();});
bindPager('collection',()=>collectionPage,n=>collectionPage=n,()=>collectionMatches().length,renderCollection);
function resetRoute(route){if(!window.confirm('將會清空當前畫面資料，確定嗎？'))return;if(route==='a'){update(s=>s.targets=[]);targetPage=0;$('target-search').value='';$('target-results').innerHTML='';renderTargets();calculate();}else{clearMother();$('material-search').value='';}notify('');}
$('target-reset').addEventListener('click',()=>safe(()=>resetRoute('a')));$('material-reset').addEventListener('click',()=>safe(()=>resetRoute('b')));
function historyStamp(at){const d=new Date(at);if(!Number.isFinite(d.getTime()))return '<span>日期未確認</span>';const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d),v=key=>parts.find(p=>p.type===key).value;return `<span class="journal-date">${v('year')}/${v('month')}/${v('day')}</span> <span class="journal-clock">${v('hour')}:${v('minute')}:${v('second')}</span>`;}
function renderHistory(){const pages=Math.max(1,Math.ceil(state.history.length/40));historyPage=Math.min(historyPage,pages-1);$('history-list').innerHTML=state.history.slice(historyPage*40,(historyPage+1)*40).map((x,i)=>`<article class="journal-item"><div class="journal-item-head"><time>${historyStamp(x.at)}</time><button type="button" class="journal-remove" data-delete-history="${historyPage*40+i}" aria-label="刪除此筆工作記錄">×</button></div><p>${h(String(x.text??'').replace(/紀錄/g,'記錄'))}</p></article>`).join('')||'<div class="history-empty">還沒有記錄。</div>';$('history-page').textContent=`${historyPage+1} / ${pages} 頁 · ${state.history.length} 筆`;$('history-prev').disabled=!historyPage;$('history-next').disabled=historyPage+1>=pages;}
$('history-list').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-delete-history]');if(!b)return;const index=Number(b.dataset.deleteHistory);if(!Number.isInteger(index)||index<0||index>=state.history.length)return;if(!window.confirm('確定刪除此筆工作記錄？'))return;update(s=>s.history.splice(index,1));renderHistory();}));
$('history-prev').addEventListener('click',()=>{historyPage=Math.max(0,historyPage-1);renderHistory();});$('history-next').addEventListener('click',()=>{historyPage++;renderHistory();});
$('note-form').addEventListener('submit',event=>{event.preventDefault();safe(()=>{const text=$('work-note').value.trim();if(!text)return;update(s=>s.history.unshift({at:new Date().toISOString(),kind:'note',text}));$('work-note').value='';historyPage=0;renderHistory();});});
$('backup').addEventListener('click',backup);
function csvText(rows){return '\uFEFF'+rows.map(r=>r.map(c=>'"'+String(c??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');}
$('export-stock').addEventListener('click',()=>download('ff14-inventory.csv',csvText([['item_id','物品','庫存'],...Object.entries(state.inventory).map(([id,q])=>[id,e.name(Number(id)),q])]),'text/csv;charset=utf-8'));
$('export-plan').addEventListener('click',()=>{if(!plan)return;download('ff14-material-plan.csv',csvText([['item_id','物品','直接份額','條件份額','已啟用需求','現貨抵扣','還缺','批次','產出','剩餘'],...plan.rows.filter(r=>!r.pureTarget).map(r=>[r.item,e.name(r.item),r.direct,r.conditional,r.need,r.usedStock,r.shortage,r.batches,r.produced,r.surplus])]),'text/csv;charset=utf-8');});
$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const text=await file.text();if(file.name.endsWith('.json')){const next=S.validate(JSON.parse(text));e.normalize(next.targets);importPending={type:'backup',next};$('import-preview').innerHTML=`<div class="warning">這份備份有 ${Object.keys(next.inventory).length} 項庫存、${Object.keys(next.completion).length} 個完成身分、${next.targets.length} 個目標。套用將還原整份本機資料；先匯出目前備份以便撤回。</div><button id="apply-import">先備份目前資料，再還原</button>`;}else{const changes=S.csvImport(text,e);importPending={type:'merge',changes};$('import-preview').innerHTML=`<div class="warning">將合併 ${Object.keys(changes.inventory).length} 項庫存、${Object.keys(changes.completion).length} 個完成身分。同 ID 使用匯入值；未出現在檔案中的進度與人工檢閱不變。</div><button id="apply-import">先備份，再套用匯入值</button>`;}}catch(err){importPending=null;$('import-preview').textContent='匯入未套用：'+err.message;}event.target.value='';});
$('import-preview').addEventListener('click',event=>safe(()=>{if(event.target.id!=='apply-import'||!importPending)return;backup();if(importPending.type==='backup'){storageBlocked=false;commit(importPending.next);}else commit(S.merge(state,importPending.changes));importPending=null;$('import-preview').textContent='已保存匯入結果；原 Google Sheets 沒有修改。';renderTargets();calculate();renderMother();}));
$('coverage').innerHTML=`<p><strong>${fmt(db.recipes.length)}</strong> 條有成品配方；<strong>${fmt(db.recipes.filter(r=>r.tracked).length)}</strong> 條製作筆記；<strong>${db.unlocks.length}</strong> 項道具效果可直接核對的永久收藏。另有 <strong>${db.pendingUnlocks.length}</strong> 個候選待核對。</p><p>${h(db.provenance.scope)}</p><details><summary>來源快照</summary><p>Collection commit：${h(db.provenance.collectionCommit)}<br>繁中資料 commit：${h(db.provenance.tcCommit)}<br>${h(db.provenance.canonicalNames.replace(/紀錄/g,'記錄'))}</p></details><p>待核對候選：${db.pendingUnlocks.map(u=>h(e.name(u.item))).join('、')||'無'}</p>`;
$('dataset-count').textContent=fmt(db.recipes.length)+' 條來源配方';
renderTargets();calculate();renderMother();


showTab('home');
