'use strict';
const db=FF14_CATALOG,e=FF14Core.createEngine(db),S=FF14State,$=id=>document.getElementById(id);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const h=escapeHtml,fmt=n=>Number(n||0).toLocaleString('zh-TW'),byId=id=>e.items.get(Number(id));
let state=S.empty(),plan=null,zero=null,tab='a',collectionPage=0,importPending=null;
try{const stored=localStorage.getItem(S.KEY);if(stored)state=S.validate(JSON.parse(stored));else if(globalThis.FF14_BOOTSTRAP)state=S.validate(globalThis.FF14_BOOTSTRAP);}catch(err){$('notice').className='warning';$('notice').textContent='原備份讀取失敗，尚未覆蓋瀏覽器資料。請先匯出原資料或使用備份恢復：'+err.message;}
let storageBlocked=!!$('notice').textContent;
function notify(message,error=false){$('notice').className=error?'warning':'inline-note';$('notice').textContent=message;}
function save(){if(storageBlocked)throw Error('原資料尚未恢復，禁止覆蓋');try{localStorage.setItem(S.KEY,JSON.stringify(state));$('save-status').textContent='已儲存於此瀏覽器 · '+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'});}catch(err){notify('無法保存，請立即匯出備份：'+err.message,true);throw err;}}
function commit(next){const old=state;state=next;try{save();}catch(err){state=old;throw err;}}
function update(fn){const next=structuredClone(state);fn(next);commit(next);}
function safe(fn){try{return fn();}catch(err){notify(err.message,true);}}
function download(name,text,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function backup(){if(storageBlocked){download('ff14-original-recovery.json',localStorage.getItem(S.KEY)||'{}');return;}download('ff14-workbench-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2));}
const titles={a:['指定成品，展開備料','加入這次要做的東西，工作台會一起計算庫存、批次與缺料。'],b:['從素材，找到收藏用途','先保留完整下游母清單，再把選定目標交給同一套備料計算。'],stock:['盤點背包，少做一點','填好現貨，讓每一層半成品都能正確切斷上游需求。'],collection:['一步一步，完成收藏','製作筆記與永久收藏共用介面，各自保留正確的完成身分。'],history:['留下紀錄，下次接著做','實際製作、盤點與工作備註，都留在這個工作台。'],data:['帶著資料，繼續旅程','保留備份，也確認配方來源與目前可使用的範圍。']};
function showTab(key){tab=key;document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!=='tab-'+key);document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===key));$('page-title').textContent=titles[key][0];$('page-description').textContent=titles[key][1];if(key==='stock')renderStock();if(key==='collection')renderCollection();if(key==='history')renderHistory();}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
function itemMatches(id,q){const x=byId(id);return x&&(x.name.includes(q)||String(id)===q);}
function recipeLabel(r){return r.job+' · Lv.'+r.level+' · '+r.scope+' · 每批 '+r.yieldQty+' 個';}
function recipeSearch(){const q=$('target-search').value.trim();if(!q){$('target-results').innerHTML='';return;}const rs=db.recipes.filter(r=>itemMatches(r.item,q)).sort((a,b)=>Number(b.tracked)-Number(a.tracked)||a.level-b.level||a.id-b.id).slice(0,35);$('target-results').innerHTML=rs.map(r=>`<div class="search-row"><div>${h(e.name(r.item))}<small>${h(recipeLabel(r))}${r.quest?' · 有任務条件':''}${r.expert?' · 專家配方':''}${r.specialist?' · 需專用條件':''}</small></div><button data-add="${r.id}">加入</button></div>`).join('')||'<div class="empty">沒有符合的配方。</div>';}
$('target-search').addEventListener('input',recipeSearch);
$('target-results').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-add]');if(!b)return;const recipe=Number(b.dataset.add);update(s=>{s.targets.push({mode:'craft',recipe,qty:1});s.targets=e.normalize(s.targets);});renderTargets();calculate();notify('已加入本次目標。');}));
function renderTargets(){const ts=state.targets;$('target-count').textContent=ts.length+' 項';$('targets').innerHTML=ts.length?`<div class="table-scroll"><table><thead><tr><th>成品</th><th>目的</th><th>數量</th><th></th></tr></thead><tbody>${ts.map((t,i)=>`<tr><td>${h(e.name(t.item||e.recipes.get(t.recipe)?.item))}<div class="inline-note">${t.recipe?h(e.recipes.get(t.recipe).job):'使用道具，完成永久登錄'}</div></td><td>${t.mode==='completion'?'製作筆記':t.mode==='unlock'?'永久收藏':'指定製作'}</td><td>${t.mode==='craft'?`<input type="number" min="1" max="999999" aria-label="${h(e.name(t.item))}需求量" value="${t.qty}" data-target-qty="${i}">`:'1'}</td><td><button class="secondary" data-remove="${i}" aria-label="移除${h(e.name(t.item))}">移除</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">從上方搜尋，加入第一個成品。</div>';}
$('targets').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-remove]');if(!b)return;update(s=>s.targets.splice(Number(b.dataset.remove),1));renderTargets();calculate();}));
$('targets').addEventListener('change',event=>safe(()=>{if(!event.target.matches('[data-target-qty]'))return;const qty=FF14Core.integer(event.target.value);if(!qty)throw Error('目標數量至少為 1');update(s=>s.targets[Number(event.target.dataset.targetQty)].qty=qty);calculate();}));
function calculate(){plan=null;zero=null;$('route-issues').innerHTML='';try{plan=e.solve(state.targets,state.inventory,state.preferences);zero=e.solve(state.targets,{},state.preferences);renderPlan();}catch(err){renderPlan();const d=err.detail||{};$('route-issues').innerHTML=`<div class="error">${h(err.message)}${d.choices?`<div class="route-choice">${d.choices.map(r=>`<button class="secondary" data-route-item="${d.item}" data-route="${r.id}">${h(recipeLabel(r))}<small> ${r.materials.filter(([id])=>byId(id)?.category!=='水晶').map(([id,q])=>h(e.name(id))+' ×'+q).join('、')}</small></button>`).join('')}</div>`:''}</div>`;}}
$('calculate').addEventListener('click',calculate);
$('route-issues').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-route]');if(!b)return;update(s=>s.preferences[b.dataset.routeItem]=Number(b.dataset.route));calculate();}));
const categoryOrder=['鍊金原料','食材','木材','皮革','骨材','石材','金屬','布料','水產品','其他'];
function table(headers,rows){return rows.length?`<div class="table-scroll"><table><thead><tr>${headers.map(x=>'<th>'+h(x)+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')}</tbody></table></div>`:'<div class="empty">目前沒有項目。</div>';}
function renderPlan(){
 $('stats').innerHTML=plan?[['製作批數',plan.crafts.reduce((s,c)=>s+c.batches,0)],['底材缺料種類',plan.raw.filter(r=>r.shortage>0).length],['現貨已抵扣種類',plan.rows.filter(r=>r.usedStock>0).length],['目標數',plan.targets.length]].map(([label,n])=>`<div class="stat"><strong>${fmt(n)}</strong><span>${label}</span></div>`).join(''):'<div class="empty">加入目標後顯示計算結果。</div>';
 if(!plan){for(const id of ['tree','shortages','crafts','zero-raw'])$(id).innerHTML='<div class="empty">沒有可顯示的計算結果。</div>';return;}
 const rowMap=new Map(plan.rows.map(r=>[r.item,r])),expanded=new Set();
 const rootRows=plan.rows.filter(r=>!r.pureTarget&&r.direct>0);const roots=new Set(rootRows.map(r=>r.item));
 function gate(r,depth=0){if(!plan.chosen[r.item])return '';const recipe=e.recipes.get(plan.chosen[r.item]),sig=x=>JSON.stringify(x.materials.filter(([id])=>byId(id)?.category!=='水晶').slice().sort((a,b)=>a[0]-b[0])),eq=e.producers.get(r.item).filter(x=>x.yieldQty===recipe.yieldQty&&sig(x)===sig(recipe));const jobs=[...new Set(eq.map(x=>x.job))].join('／');if(r.batches===0)return `<div class="gate"><b>若不足：【${h(jobs)}】</b><div>現貨足夠，這份上游已歸零。</div></div>`;
  if(expanded.has(r.item))return '<div class="use">共用備料，見上方 '+h(e.name(r.item))+' 的唯一展開位置。</div>';expanded.add(r.item);
  const children=plan.shares.filter(s=>s.parent===r.item);return `<div class="gate"><b>若不足：【${h(jobs)}】</b><div>製作 ${r.batches} 批 ｜ 產出 ×${r.produced} ｜ 使用 ×${Math.max(0,r.need-r.usedStock)} ｜ 剩餘 ×${r.surplus}</div>${children.map(s=>{const child=rowMap.get(s.item);if(!child)return '';const cross=byId(s.item)?.category!==byId(r.item)?.category?'〔'+h(byId(s.item)?.category||'其他')+'〕':'';const ref=roots.has(s.item)?'<div class="use">另有直接用途；其全域缺口在自己的主列集中處理。</div>':gate(child,depth+1);return `<div style="margin-left:${Math.min(depth,6)*3}px">${h(e.name(s.item))}${cross} ×${fmt(s.qty)} <span class="muted">（這條條件份額）</span>${child.usedStock?'<span class="badge">全域現貨已抵 '+fmt(child.usedStock)+'</span>':''}${ref}</div>`;}).join('')}</div>`;
 }
 const categories=[...new Set(rootRows.map(r=>byId(r.item)?.category||'其他'))].sort((a,b)=>{const ai=categoryOrder.indexOf(a),bi=categoryOrder.indexOf(b);return (ai<0?99:ai)-(bi<0?99:bi)||a.localeCompare(b,'zh-TW');});
 $('tree').innerHTML=categories.map(cat=>`<div class="tree-category"><h3>${h(cat)}</h3>${rootRows.filter(r=>(byId(r.item)?.category||'其他')===cat).map(r=>`<article class="tree-node ${state.review[r.item]?'reviewed':''}"><div class="node-head"><input type="checkbox" aria-label="已檢閱${h(e.name(r.item))}" data-review="${r.item}" ${state.review[r.item]?'checked':''}><strong>${h(e.name(r.item))}</strong><span class="qty">直接需求 ×${fmt(r.direct)}</span><label class="stock-value">現貨 <input type="number" min="0" aria-label="${h(e.name(r.item))}庫存" value="${state.inventory[r.item]||0}" data-stock="${r.item}"></label></div><div class="node-body"><div>${r.reserve?`<div>【本次目標保留】×${r.reserve}</div>`:''}${r.uses.filter(s=>s.direct).map(s=>`<div>→ ${h(e.name(s.parent))} ×${s.output}（本素材 ×${s.qty}）</div>`).join('')}<div class="use">本次已啟用總量 ×${r.need}；現貨抵扣 ×${r.usedStock}${r.conditional?'；另有條件份額 ×'+r.conditional:''}</div></div>${gate(r)}</div></article>`).join('')}</div>`).join('')||'<div class="empty">目前目標沒有直接素材列；請查看底層缺料及製作批次。</div>';
 $('shortages').innerHTML=table(['素材','還缺','已啟用需求','盤點現貨'],plan.raw.filter(r=>r.shortage>0).map(r=>[h(e.name(r.item)),`<strong>${fmt(r.shortage)}</strong>`,fmt(r.need),`<input type="number" min="0" aria-label="${h(e.name(r.item))}庫存" data-stock="${r.item}" value="${state.inventory[r.item]||0}">`]));
 $('crafts').innerHTML=table(['製作物品','批次／產量','分流與停點','實際紀錄'],plan.crafts.map(c=>{const r=rowMap.get(c.item);return [h(e.name(c.item))+'<div class="inline-note">'+h(c.job)+'</div>',`${c.batches} 批<br>每批 ${c.yieldQty}<br>產出 ${c.produced}`,`保留 ×${r.reserve}<br>投入下游 ×${r.need-r.reserve}<br>批次剩餘 ×${r.surplus}`,`<button class="secondary" data-craft="${c.recipe}" data-batches="${c.batches}">記錄已製作</button>`];}));
 $('zero-raw').innerHTML=table(['分類','原料','從零需求'],(zero?.raw||[]).map(r=>[h(byId(r.item)?.category),h(e.name(r.item)),fmt(r.need)]));
}
document.addEventListener('change',event=>safe(()=>{if(event.target.matches('[data-stock]')){const id=event.target.dataset.stock,n=FF14Core.integer(event.target.value,'庫存');update(s=>s.inventory[id]=n);calculate();if(tab==='stock')renderStock();}if(event.target.matches('[data-review]')){update(s=>s.review[event.target.dataset.review]=event.target.checked);renderPlan();}if(event.target.matches('[data-completion]')){update(s=>s.completion[event.target.dataset.completion]=event.target.checked);renderCollection();renderMother();}}));
$('crafts').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-craft]');if(!b)return;const r=e.recipes.get(Number(b.dataset.craft)),n=Number(b.dataset.batches);if(!window.confirm('確認你已在遊戲中製作 '+e.name(r.item)+' '+n+' 批？\n將扣除已盤點材料、增加成品；不會自動完成永久收藏。'))return;const pure=plan.pureTargets.includes(r.item);const next=S.recordCraft(state,e,r.id,n);if(pure)next.targets=next.targets.filter(t=>!(t.mode==='craft'&&t.recipe===r.id));commit(next);renderTargets();calculate();notify('已保存實際製作紀錄與庫存變動。');}));
function renderStock(){const q=$('stock-search').value.trim(),list=q?db.items.filter(x=>itemMatches(x.id,q)).slice(0,100):db.items.filter(x=>Object.hasOwn(state.inventory,x.id));$('stock-items').innerHTML=table(['物品','分類','現有數量'],list.map(x=>[h(x.name)+'<div class="inline-note">ID '+x.id+'</div>',h(x.category),`<input type="number" min="0" aria-label="${h(x.name)}庫存" data-stock="${x.id}" value="${state.inventory[x.id]||0}">`]));}
$('stock-search').addEventListener('input',renderStock);
function materialSearch(){const q=$('material-search').value.trim();$('material-results').innerHTML=q?db.items.filter(x=>itemMatches(x.id,q)).slice(0,30).map(x=>`<div class="search-row"><div>${h(x.name)}<small>${h(x.category)} · ID ${x.id}</small></div><button data-material="${x.id}">找下游</button></div>`).join(''):'';}
$('material-search').addEventListener('input',materialSearch);
$('material-results').addEventListener('click',event=>safe(()=>{const b=event.target.closest('[data-material]');if(!b)return;const mother=e.downstream(Number(b.dataset.material),state.completion);const groups=new Map();for(const t of mother.targets){const r=e.recipes.get(t.recipe),label=r?r.job+' · '+Math.floor(r.level/10)*10+'–'+(Math.floor(r.level/10)*10+9)+' 級':'永久收藏';if(!groups.has(label))groups.set(label,[]);groups.get(label).push(t.key);}const batches=[];for(const [label,keys] of groups)for(let i=0;i<keys.length;i+=20)batches.push({id:batches.length+1,label,keys:keys.slice(i,i+20)});update(s=>s.mother={...mother,batches,issuedKeys:[],selected:mother.targets.filter(t=>!t.done).map(t=>t.key),createdAt:new Date().toISOString(),page:0});renderMother();}));
function renderMother(){const m=state.mother;if(!m){$('mother').innerHTML='';return;}const current=m.targets.map(t=>({...t,done:state.completion[t.completionKey]===true}));const selected=current.filter(t=>m.selected.includes(t.key)&&!t.done),page=m.page||0,pages=Math.max(1,Math.ceil(current.length/40));let quantityText='選定目標交給 Route A 後，全域計算保留量';try{const p=e.solve(selected,{},state.preferences);quantityText='選定目標從零需求：'+fmt(p.rows.find(r=>r.item===m.start)?.need||0)+' 個 '+e.name(m.start);}catch(err){quantityText='總需求尚待選擇製作路線：'+err.message;}
 let globalText;try{const all=e.solve(current.filter(t=>!t.done),{},state.preferences);globalText='完整母清單未完成目標：'+fmt(all.rows.find(r=>r.item===m.start)?.need||0)+' 個（從零，全域合併批次）';}catch(err){globalText='完整母清單總需求待核對路線：'+err.message;}
 const issued=new Set(m.issuedKeys||[]);const batchHtml=(m.batches||[]).map(batch=>{const ts=current.filter(t=>batch.keys.includes(t.key)&&!t.done);let need='待選路線';try{need=fmt(e.solve(ts,{},state.preferences).rows.find(r=>r.item===m.start)?.need||0);}catch{}return `<div class="search-row"><div>第 ${batch.id} 批 · ${h(batch.label)}<small>${batch.keys.length} 項 · 此批從零需要素材 ${need} 個 · 已交給工作台 ${batch.keys.filter(k=>issued.has(k)).length} 項</small></div><button class="secondary" data-batch="${batch.id}">選取此批</button></div>`;}).join('');
 $('mother').innerHTML=`<div class="card"><div class="section-head"><div><h2>${h(e.name(m.start))} · 下游母清單</h2><p>找到 ${m.recipes.length} 條相關配方；有效收藏目標 ${current.length} 項，已完成 ${current.filter(t=>t.done).length} 項。選取 ${selected.length} 項。</p></div><button id="send-route-a" ${!selected.length?'disabled':''}>選定目標交給 Route A</button></div><div class="warning">${!state.sheetProgressImported&&!Object.keys(state.completion).length?'尚未匯入你的製作圖鑑進度，目前先以未完成列出。<br>':''}${h(globalText)}<br>${h(quantityText)}<br>配方圖涵蓋來源快照全部 Recipe；現行可用性／特殊流程仍需確認。${m.pending.length?' 有 '+m.pending.length+' 個收藏候選尚未納入。':''}</div>${batchHtml?`<details><summary>分批製作 · ${m.batches.length} 批 · 尚未交給工作台 ${current.filter(t=>!t.done&&!issued.has(t.key)).length} 項</summary><p>批次只方便分段操作；各批從零數量不可相加當成全案需求。工作台會合併已交入的目標，庫存與批次剩餘只計一次。</p>${batchHtml}</details>`:''}<div class="controls"><button class="secondary" id="select-unfinished">選取全部未完成</button><button class="secondary" id="clear-selection">清除選取</button></div>${table(['納入','目標','完成種類','已完成'],current.slice(page*40,(page+1)*40).map(t=>[`<input type="checkbox" aria-label="納入${h(e.name(t.item))}" data-mother-select="${h(t.key)}" ${m.selected.includes(t.key)&&!t.done?'checked':''} ${t.done?'disabled':''}>`,h(e.name(t.item))+(t.recipe?'<div class="inline-note">'+h(recipeLabel(e.recipes.get(t.recipe)))+'</div>':''),t.mode==='completion'?'製作筆記':'永久收藏',`<input type="checkbox" aria-label="完成${h(e.name(t.item))}" data-completion="${h(t.completionKey)}" ${t.done?'checked':''}>`]))}<div class="pager"><button class="secondary" id="mother-prev" ${page===0?'disabled':''}>上一頁</button><span>${page+1} / ${pages} 頁</span><button class="secondary" id="mother-next" ${page+1>=pages?'disabled':''}>下一頁</button></div><p>分頁只改變畫面，母集合與全域需求不變。交給 Route A 時，同一完成身分會去重。</p></div>`;
}
$('mother').addEventListener('click',event=>safe(()=>{const id=event.target.id,button=event.target.closest('[data-batch]');if(!button&&!['select-unfinished','clear-selection','mother-prev','mother-next','send-route-a'].includes(id))return;if(button){const batch=state.mother.batches.find(b=>b.id===Number(button.dataset.batch));update(s=>s.mother.selected=batch.keys.filter(k=>{const t=s.mother.targets.find(t=>t.key===k);return s.completion[t.completionKey]!==true;}));}if(id==='select-unfinished')update(s=>s.mother.selected=s.mother.targets.filter(t=>state.completion[t.completionKey]!==true).map(t=>t.key));if(id==='clear-selection')update(s=>s.mother.selected=[]);if(id==='mother-prev')update(s=>s.mother.page=Math.max(0,s.mother.page-1));if(id==='mother-next')update(s=>s.mother.page++);if(id==='send-route-a'){const ts=state.mother.targets.filter(t=>state.mother.selected.includes(t.key)&&state.completion[t.completionKey]!==true);update(s=>{s.targets=e.normalize([...s.targets,...ts]);s.mother.issuedKeys=[...new Set([...(s.mother.issuedKeys||[]),...ts.map(t=>t.key)])];});renderTargets();calculate();showTab('a');notify('已交給 Route A。已交入目標一起計算，共用庫存與批次不重複。');}renderMother();}));
$('mother').addEventListener('change',event=>safe(()=>{if(!event.target.matches('[data-mother-select]'))return;const key=event.target.dataset.motherSelect;update(s=>{s.mother.selected=s.mother.selected.filter(k=>k!==key);if(event.target.checked)s.mother.selected.push(key);});renderMother();}));
function renderCollection(){const q=$('collection-search').value.trim(),kind=$('collection-kind').value,only=$('only-unfinished').checked;let list=kind==='recipe'?db.recipes.filter(r=>r.tracked).map(r=>({item:r.item,key:'recipe_completion:'+r.id,label:recipeLabel(r)})):db.unlocks.map(u=>({item:u.item,key:'permanent_unlock:'+u.item,label:u.type,evidence:u.evidence}));list=list.filter(t=>(!q||itemMatches(t.item,q))&&(!only||state.completion[t.key]!==true));const pages=Math.max(1,Math.ceil(list.length/40));collectionPage=Math.min(collectionPage,pages-1);$('collection-list').innerHTML=table(['已完成','項目','完成身分'],list.slice(collectionPage*40,(collectionPage+1)*40).map(t=>[`<input type="checkbox" aria-label="完成${h(e.name(t.item))}" data-completion="${h(t.key)}" ${state.completion[t.key]?'checked':''}>`,h(e.name(t.item))+'<div class="inline-note">'+h(t.label)+'</div>'+(t.evidence?'<details><summary>來源效果</summary>'+h(t.evidence)+'</details>':''),h(t.key)]));$('collection-page').textContent=`${collectionPage+1} / ${pages} 頁 · ${list.length} 項`;$('collection-prev').disabled=!collectionPage;$('collection-next').disabled=collectionPage+1>=pages;}
for(const id of ['collection-search','collection-kind','only-unfinished'])$(id).addEventListener('input',()=>{collectionPage=0;renderCollection();});$('collection-prev').addEventListener('click',()=>{collectionPage--;renderCollection();});$('collection-next').addEventListener('click',()=>{collectionPage++;renderCollection();});
function renderHistory(){$('history-list').innerHTML=state.history.slice(0,300).map(x=>`<div class="history-entry"><small>${h(new Date(x.at).toLocaleString('zh-TW'))}</small>${h(x.text)}</div>`).join('')||'<div class="empty">還沒有紀錄。</div>';}
$('note-form').addEventListener('submit',event=>{event.preventDefault();safe(()=>{const text=$('work-note').value.trim();if(!text)return;update(s=>s.history.unshift({at:new Date().toISOString(),kind:'note',text}));$('work-note').value='';renderHistory();});});
for(const id of ['backup','backup-top'])$(id).addEventListener('click',backup);
function csvText(rows){return '\uFEFF'+rows.map(r=>r.map(c=>'"'+String(c??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');}
$('export-stock').addEventListener('click',()=>download('ff14-inventory.csv',csvText([['item_id','物品','庫存'],...Object.entries(state.inventory).map(([id,q])=>[id,e.name(Number(id)),q])]),'text/csv;charset=utf-8'));
$('export-plan').addEventListener('click',()=>{if(!plan)return;download('ff14-material-plan.csv',csvText([['item_id','物品','直接份額','條件份額','已啟用需求','現貨抵扣','還缺','批次','產出','剩餘'],...plan.rows.filter(r=>!r.pureTarget).map(r=>[r.item,e.name(r.item),r.direct,r.conditional,r.need,r.usedStock,r.shortage,r.batches,r.produced,r.surplus])]),'text/csv;charset=utf-8');});
$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const text=await file.text();if(file.name.endsWith('.json')){const next=S.validate(JSON.parse(text));e.normalize(next.targets);importPending={type:'backup',next};$('import-preview').innerHTML=`<div class="warning">這份備份有 ${Object.keys(next.inventory).length} 項庫存、${Object.keys(next.completion).length} 個完成身分、${next.targets.length} 個目標。套用將還原整份本機資料；先匯出目前備份以便撤回。</div><button id="apply-import">先備份目前資料，再還原</button>`;}else{const changes=S.csvImport(text,e);importPending={type:'merge',changes};$('import-preview').innerHTML=`<div class="warning">將合併 ${Object.keys(changes.inventory).length} 項庫存、${Object.keys(changes.completion).length} 個完成身分。同 ID 使用匯入值；未出現在檔案中的進度與人工檢閱不變。</div><button id="apply-import">先備份，再套用匯入值</button>`;}}catch(err){importPending=null;$('import-preview').textContent='匯入未套用：'+err.message;}event.target.value='';});
$('import-preview').addEventListener('click',event=>safe(()=>{if(event.target.id!=='apply-import'||!importPending)return;backup();if(importPending.type==='backup'){storageBlocked=false;commit(importPending.next);}else commit(S.merge(state,importPending.changes));importPending=null;$('import-preview').textContent='已保存匯入結果；原 Google Sheets 沒有修改。';renderTargets();calculate();renderMother();}));
$('coverage').innerHTML=`<p><strong>${fmt(db.recipes.length)}</strong> 條有成品配方；<strong>${fmt(db.recipes.filter(r=>r.tracked).length)}</strong> 條製作筆記；<strong>${db.unlocks.length}</strong> 項道具效果可直接核對的永久收藏。另有 <strong>${db.pendingUnlocks.length}</strong> 個候選待核對。</p><p>${h(db.provenance.scope)}</p><details><summary>來源快照</summary><p>Collection commit：${h(db.provenance.collectionCommit)}<br>繁中資料 commit：${h(db.provenance.tcCommit)}<br>${h(db.provenance.canonicalNames)}</p></details><p>待核對候選：${db.pendingUnlocks.map(u=>h(e.name(u.item))).join('、')||'無'}</p>`;
$('dataset-count').textContent=fmt(db.recipes.length)+' 條來源配方';
renderTargets();calculate();renderMother();
