(function(root){
'use strict';const VERSION=1,KEY='ff14-workbench-v1';
function empty(){return {version:VERSION,inventory:{},completion:{},review:{},preferences:{},targets:[],mother:null,history:[]};}
function validate(s){if(!s||s.version!==VERSION)throw Error('不支援的備份版本');for(const key of ['inventory','completion','review','preferences']){if(!s[key]||typeof s[key]!=='object'||Array.isArray(s[key]))throw Error('備份缺少 '+key);for(const [id,value] of Object.entries(s[key])){if(['inventory','preferences'].includes(key)&&(!/^\d+$/.test(id)||!Number.isSafeInteger(value)||value<0))throw Error('數量或身分欄位不正確');if(['completion','review'].includes(key)&&typeof value!=='boolean')throw Error('勾選欄位不正確');}}if(!Array.isArray(s.targets)||!Array.isArray(s.history))throw Error('備份缺少工作記錄');return structuredClone(s);}
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV 引號未結束');row.push(cell);if(row.some(Boolean))rows.push(row);if(rows[0]?.[0])rows[0][0]=rows[0][0].replace(/^\uFEFF/,'');return rows;}
function csvImport(text,engine){const rows=csv(text),headers=rows.shift()||[],find=names=>headers.findIndex(h=>names.includes(h.trim()));const rid=find(['recipe_id','配方ID']),iid=find(['item_id','物品ID']),done=find(['已登錄','已完成']),stock=find(['庫存','現有庫存','現有庫存（只填這欄）','quantity']),ctype=find(['completion_type']),cid=find(['completion_id']);const changes={inventory:{},completion:{}};const seen=new Set();for(const row of rows){if(row.every(x=>!x))continue;if(stock>=0&&iid>=0){const id=Number(row[iid]),n=Number(row[stock]);if(!engine.items.has(id)||!Number.isSafeInteger(n)||n<0)throw Error('庫存列的 ID／數量不正確');if(seen.has('i'+id))throw Error('同一庫存 ID 重複，請先整理');seen.add('i'+id);changes.inventory[id]=n;}else if(done>=0){let key;if(ctype>=0&&cid>=0){const type=row[ctype];if(!['recipe_completion','permanent_unlock'].includes(type))throw Error('不支援的完成種類');key=type+':'+Number(row[cid]);}else if(rid>=0&&engine.recipes.has(Number(row[rid])))key='recipe_completion:'+Number(row[rid]);else throw Error('找不到可靠的完成身分，不能按名称配對');const value=String(row[done]).toUpperCase();if(!['TRUE','FALSE'].includes(value))throw Error('勾選值必須是 TRUE／FALSE');if(seen.has(key))throw Error('完成身分重複');seen.add(key);changes.completion[key]=value==='TRUE';}else throw Error('CSV 缺少庫存或完成欄位及身分 ID');}return changes;}
function merge(s,changes){const n=validate(s);Object.assign(n.inventory,changes.inventory);Object.assign(n.completion,changes.completion);return n;}
function recordCraft(s,engine,rid,batches){const n=validate(s),r=engine.recipes.get(Number(rid));if(!r||!Number.isSafeInteger(batches)||batches<=0)throw Error('製作批次不正確');for(const [id,q] of r.materials){if(engine.items.get(id)?.category==='水晶')continue;if((n.inventory[id]||0)<q*batches)throw Error(engine.name(id)+'的已盤點庫存不足；請先補齊實際數量');}
 for(const [id,q] of r.materials){if(engine.items.get(id)?.category!=='水晶')n.inventory[id]-=q*batches;}n.inventory[r.item]=(n.inventory[r.item]||0)+r.yieldQty*batches;if(r.tracked)n.completion['recipe_completion:'+r.id]=true;n.targets=n.targets.filter(t=>!(t.mode==='completion'&&t.recipe===r.id));n.history.unshift({at:new Date().toISOString(),text:'已記錄製作 '+engine.name(r.item)+' ×'+r.yieldQty*batches+'（'+batches+' 批）；扣除已盤點材料，增加成品。碎晶／水晶／晶簇未追蹤。',kind:'craft',recipe:r.id,batches});return n;}
const api={empty,validate,csv,csvImport,merge,recordCraft,KEY};if(typeof module!=='undefined')module.exports=api;root.FF14State=api;
})(globalThis);
